Add SEARCH_ROOT parameter
This allows for build systems that utilize symlinks in their test results trees
as 'find' by default will skip processing symlinks.  This approach is taken
additionally since using the all-or-nothing 'find' options to enable symlink
traversal yields poor runtime behavior.  The motivating build system is bazel.

diff --git a/hooks/pre-exit b/hooks/pre-exit
--- a/hooks/pre-exit
+++ b/hooks/pre-exit
@@ -5,6 +5,8 @@ TOKEN_ENV_NAME="${BUILDKITE_PLUGIN_TEST_COLLECTOR_API_TOKEN_ENV_NAME:-BUILDKITE_
 
 FILES_PATTERN="${BUILDKITE_PLUGIN_TEST_COLLECTOR_FILES:-}"
 
+SEARCH_ROOT="${BUILDKITE_PLUGIN_TEST_COLLECTOR_SEARCH_ROOT:-.}"
+
 FORMAT="${BUILDKITE_PLUGIN_TEST_COLLECTOR_FORMAT:-}"
 
 TIMEOUT="${BUILDKITE_PLUGIN_TEST_COLLECTOR_TIMEOUT:-30}"
@@ -86,10 +88,10 @@ fi
 matching_files=()
 while IFS=$'' read -r matching_file ; do
   matching_files+=("$matching_file")
-done < <(find . -path "./${FILES_PATTERN}")
+done < <(find ${SEARCH_ROOT} -path "${SEARCH_ROOT}/${FILES_PATTERN}")
 
 if [[ "${#matching_files[@]}" -eq "0" ]]; then
-  echo "No files found matching '${FILES_PATTERN}'"
+  echo "No files found matching '${FILES_PATTERN}' in './${SEARCH_ROOT}' (abspath: $( (cd "$SEARCH_ROOT" && pwd) || echo "<search_root not found>"))"
   exit 1
 fi
 
